version: 0.2

env:
  variables:
    TZ: "Asia/Seoul"

phases:
  install:
    commands:
      - echo Entered the install phase...

  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 948216186415.dkr.ecr.ap-northeast-2.amazonaws.com
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - IMAGE_TAGS=$(date "+%y%m%d%H%M%S")

  build:
    commands:
      - echo Build started on `date`
      - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO}:${IMAGE_TAGS} .
      - sed -i "s|CHANGEME|$IMAGE_TAGS|g" taskdef.json

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO}:${IMAGE_TAGS}
      - printf '[{"name":"wsi-api-ctn"}, "imageUri":"%s"]' ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO}:${IMAGE_TAGS} > imageDetail.json
      - cat imageDetail.json

artifacts:
  files:
    - appspec.yml
    - taskdef.json
  secondary-artifacts:
    DefinitionArtifacts:
      files:
        - appspec.yml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
